title: Procesos en el flujo de trabajo de análisis de datos 
description: Desde la creación de repositorio en github hasta la estructura de la primer versión del repositorio.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman