title: Procesos en el flujo de trabajo de análisis de datos desde la creación de repositorio en github hasta la estructura de la primer versión del repositorio.
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman